// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ad.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Ad struct {
	Ref                  string      `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Brand                string      `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	Model                string      `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Price                int32       `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Options              *Ad_Options `protobuf:"bytes,5,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Ad) Reset()         { *m = Ad{} }
func (m *Ad) String() string { return proto.CompactTextString(m) }
func (*Ad) ProtoMessage()    {}
func (*Ad) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fe9fe9dbc34d4ab, []int{0}
}

func (m *Ad) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ad.Unmarshal(m, b)
}
func (m *Ad) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ad.Marshal(b, m, deterministic)
}
func (m *Ad) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ad.Merge(m, src)
}
func (m *Ad) XXX_Size() int {
	return xxx_messageInfo_Ad.Size(m)
}
func (m *Ad) XXX_DiscardUnknown() {
	xxx_messageInfo_Ad.DiscardUnknown(m)
}

var xxx_messageInfo_Ad proto.InternalMessageInfo

func (m *Ad) GetRef() string {
	if m != nil {
		return m.Ref
	}
	return ""
}

func (m *Ad) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *Ad) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *Ad) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Ad) GetOptions() *Ad_Options {
	if m != nil {
		return m.Options
	}
	return nil
}

type Ad_Options struct {
	Bluetooth            bool     `protobuf:"varint,1,opt,name=bluetooth,proto3" json:"bluetooth,omitempty"`
	Gps                  bool     `protobuf:"varint,2,opt,name=gps,proto3" json:"gps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ad_Options) Reset()         { *m = Ad_Options{} }
func (m *Ad_Options) String() string { return proto.CompactTextString(m) }
func (*Ad_Options) ProtoMessage()    {}
func (*Ad_Options) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fe9fe9dbc34d4ab, []int{0, 0}
}

func (m *Ad_Options) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ad_Options.Unmarshal(m, b)
}
func (m *Ad_Options) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ad_Options.Marshal(b, m, deterministic)
}
func (m *Ad_Options) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ad_Options.Merge(m, src)
}
func (m *Ad_Options) XXX_Size() int {
	return xxx_messageInfo_Ad_Options.Size(m)
}
func (m *Ad_Options) XXX_DiscardUnknown() {
	xxx_messageInfo_Ad_Options.DiscardUnknown(m)
}

var xxx_messageInfo_Ad_Options proto.InternalMessageInfo

func (m *Ad_Options) GetBluetooth() bool {
	if m != nil {
		return m.Bluetooth
	}
	return false
}

func (m *Ad_Options) GetGps() bool {
	if m != nil {
		return m.Gps
	}
	return false
}

type Ads struct {
	Ads                  []*Ad    `protobuf:"bytes,1,rep,name=ads,proto3" json:"ads,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ads) Reset()         { *m = Ads{} }
func (m *Ads) String() string { return proto.CompactTextString(m) }
func (*Ads) ProtoMessage()    {}
func (*Ads) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fe9fe9dbc34d4ab, []int{1}
}

func (m *Ads) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ads.Unmarshal(m, b)
}
func (m *Ads) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ads.Marshal(b, m, deterministic)
}
func (m *Ads) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ads.Merge(m, src)
}
func (m *Ads) XXX_Size() int {
	return xxx_messageInfo_Ads.Size(m)
}
func (m *Ads) XXX_DiscardUnknown() {
	xxx_messageInfo_Ads.DiscardUnknown(m)
}

var xxx_messageInfo_Ads proto.InternalMessageInfo

func (m *Ads) GetAds() []*Ad {
	if m != nil {
		return m.Ads
	}
	return nil
}

type CreateAdRequest struct {
	Ad                   *Ad      `protobuf:"bytes,1,opt,name=ad,proto3" json:"ad,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAdRequest) Reset()         { *m = CreateAdRequest{} }
func (m *CreateAdRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAdRequest) ProtoMessage()    {}
func (*CreateAdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fe9fe9dbc34d4ab, []int{2}
}

func (m *CreateAdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAdRequest.Unmarshal(m, b)
}
func (m *CreateAdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAdRequest.Marshal(b, m, deterministic)
}
func (m *CreateAdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAdRequest.Merge(m, src)
}
func (m *CreateAdRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAdRequest.Size(m)
}
func (m *CreateAdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAdRequest proto.InternalMessageInfo

func (m *CreateAdRequest) GetAd() *Ad {
	if m != nil {
		return m.Ad
	}
	return nil
}

type CreateAdResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAdResponse) Reset()         { *m = CreateAdResponse{} }
func (m *CreateAdResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAdResponse) ProtoMessage()    {}
func (*CreateAdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fe9fe9dbc34d4ab, []int{3}
}

func (m *CreateAdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAdResponse.Unmarshal(m, b)
}
func (m *CreateAdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAdResponse.Marshal(b, m, deterministic)
}
func (m *CreateAdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAdResponse.Merge(m, src)
}
func (m *CreateAdResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAdResponse.Size(m)
}
func (m *CreateAdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAdResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Ad)(nil), "Ad")
	proto.RegisterType((*Ad_Options)(nil), "Ad.Options")
	proto.RegisterType((*Ads)(nil), "Ads")
	proto.RegisterType((*CreateAdRequest)(nil), "CreateAdRequest")
	proto.RegisterType((*CreateAdResponse)(nil), "CreateAdResponse")
}

func init() { proto.RegisterFile("ad.proto", fileDescriptor_8fe9fe9dbc34d4ab) }

var fileDescriptor_8fe9fe9dbc34d4ab = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0xc1, 0x4a, 0xf4, 0x30,
	0x14, 0x85, 0x49, 0xf3, 0xf7, 0x9f, 0xce, 0xad, 0xe0, 0x10, 0x15, 0x82, 0xcc, 0xa2, 0x14, 0x94,
	0xae, 0xb2, 0x18, 0x57, 0xe2, 0x2a, 0xfa, 0x00, 0x42, 0x96, 0xee, 0x52, 0xef, 0x1d, 0x1d, 0x18,
	0x9b, 0x98, 0xa4, 0x2f, 0xe7, 0xd3, 0x49, 0xd2, 0x91, 0xd9, 0x9d, 0xef, 0xcb, 0x21, 0x1c, 0x2e,
	0x34, 0x16, 0x95, 0x0f, 0x2e, 0xb9, 0xfe, 0x87, 0x41, 0xa5, 0x51, 0x6c, 0x80, 0x07, 0xda, 0x4b,
	0xd6, 0xb1, 0x61, 0x6d, 0x72, 0x14, 0xd7, 0x50, 0x8f, 0xc1, 0x4e, 0x28, 0xab, 0xe2, 0x16, 0xc8,
	0xf6, 0xcb, 0x21, 0x1d, 0x25, 0x5f, 0x6c, 0x81, 0x6c, 0x7d, 0x38, 0xbc, 0x93, 0xfc, 0xd7, 0xb1,
	0xa1, 0x36, 0x0b, 0x88, 0x3b, 0x58, 0x39, 0x9f, 0x0e, 0x6e, 0x8a, 0xb2, 0xee, 0xd8, 0xd0, 0xee,
	0x5a, 0xa5, 0x51, 0xbd, 0x2e, 0xca, 0xfc, 0xbd, 0xdd, 0x3e, 0xc2, 0xea, 0xe4, 0xc4, 0x16, 0xd6,
	0xe3, 0x71, 0xa6, 0xe4, 0x5c, 0xfa, 0x2c, 0x5b, 0x1a, 0x73, 0x16, 0x79, 0xe3, 0x87, 0x8f, 0x65,
	0x4f, 0x63, 0x72, 0xec, 0xb7, 0xc0, 0x35, 0x46, 0x71, 0x03, 0xdc, 0x62, 0x94, 0xac, 0xe3, 0x43,
	0xbb, 0xe3, 0x4a, 0xa3, 0xc9, 0xdc, 0xdf, 0xc3, 0xe5, 0x4b, 0x20, 0x9b, 0x48, 0xa3, 0xa1, 0xef,
	0x99, 0x62, 0x12, 0x57, 0x50, 0x59, 0x2c, 0x3f, 0x9f, 0x8a, 0x95, 0xc5, 0x5e, 0xc0, 0xe6, 0xdc,
	0x8b, 0xde, 0x4d, 0x91, 0x9e, 0x2f, 0xde, 0x40, 0x3d, 0x95, 0x0b, 0x8d, 0xf3, 0x7e, 0xfc, 0x5f,
	0xd2, 0xc3, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x69, 0x1e, 0x27, 0xc2, 0x37, 0x01, 0x00, 0x00,
}
